# Generated by Django 5.1.4 on 2025-01-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('unknown', 'Не визначено'), ('7', '7 клас'), ('8', '8 клас'), ('9', '9 клас'), ('10', '10 клас'), ('11', '11 клас'), ('teacher', 'Викладач/Куратор')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
