# Generated by Django 5.1.5 on 2025-01-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250116_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('unknown', 'Не визначено'), ('7', '7 клас'), ('8', '8 клас'), ('9', '9 клас'), ('10', '10 клас'), ('11', '11 клас'), ('teacher', 'Викладач/Куратор'), ('graduate', 'Випускник')], default='unknown', max_length=10),
        ),
    ]
