# Generated by Django 5.1.4 on 2024-12-26 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='books.category')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('title', models.CharField(default='No data', max_length=64)),
                ('author', models.CharField(default='No data', max_length=64)),
                ('year', models.CharField(default='No data', max_length=20)),
                ('tom', models.CharField(default='No data', max_length=5)),
                ('publisher', models.CharField(default='No data', max_length=64)),
                ('notes', models.CharField(default='No notes', max_length=64)),
                ('category', models.ForeignKey(default='No data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category')),
                ('subcategory', models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.subcategory')),
            ],
        ),
    ]
