# Generated by Django 5.1.5 on 2025-01-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tom',
            field=models.CharField(default='No data', max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(default='No data', max_length=64),
        ),
    ]
