# Generated by Django 5.1.5 on 2025-01-16 21:04

import os
from django.db import migrations
from tablib import Dataset
from maj_lib.settings import BASE_DIR


def import_books_data(apps, schema_editor):
    Category = apps.get_model("books", "Category")
    Publisher = apps.get_model("books", "Publisher")
    Book = apps.get_model("books", "Book")

    file_path = os.path.join(BASE_DIR, 'data_book.csv')
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Файл {file_path} не знайдено")

    with open(file_path, 'r') as fh:
        imported_data = Dataset().load(fh)

    for item in imported_data.dict:
        category = item["Category"].strip()
        publisher = item["Publisher"].strip()

        category_obj, _ = Category.objects.get_or_create(name=category)
        publisher_obj, _ = Publisher.objects.get_or_create(name=publisher)

        kwargs = {}
        if item["Quantity"]:
            kwargs['quantity'] = int(item["Quantity"])

        Book.objects.get_or_create(
            num=int(item["Num"]),
            category=category_obj,
            title=item["Title"].strip(),
            author=item["Author"].strip(),
            year=item["Year"],
            tom=item["Tom"],
            publisher=publisher_obj,
            notes=item["Notes"],
            **kwargs
        )

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_books_data),
    ]
