# Generated by Django 5.1.5 on 2025-01-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_tom_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.CharField(default='No notes', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='tom',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
