# Generated by Django 5.1.4 on 2024-12-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'category')},
        ),
    ]
