# Generated by Django 5.1.4 on 2024-12-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_subcategory_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='number',
            new_name='num',
        ),
    ]
