# Generated by Django 5.1.5 on 2025-01-15 09:25

import os
from django.db import migrations
from tablib import Dataset
from maj_lib.settings import BASE_DIR


def import_books_data(apps, schema_editor):
    Category = apps.get_model("books", "Category")
    Subcategory = apps.get_model("books", "Subcategory")
    Book = apps.get_model("books", "Book")

    file_path = os.path.join(BASE_DIR, 'data_test.csv')
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Файл {file_path} не знайдено")

    with open(file_path, 'r') as fh:
        imported_data = Dataset().load(fh)

    for item in imported_data.dict:
        category = item["Category"].strip()
        subcategory = item["SubCategory"].strip()

        category_obj, _ = Category.objects.get_or_create(name=category)
        subcategory_obj, _ = Subcategory.objects.get_or_create(
            category=category_obj, 
            name=subcategory
        )
        Book.objects.get_or_create(
            num=int(item["Num"]),
            title=item["Name"],
            author=item["Author"].strip(),
            category=category_obj,
            subcategory=subcategory_obj,
            year=item["Year"],
            tom=item["Tom"],
            publisher=item["Publisher"].strip(),
            notes=item["Notes"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20250115_1112'),
    ]

    operations = [
        migrations.RunPython(import_books_data),
    ]
