# Generated by Django 5.1.4 on 2024-12-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_number_book_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.CharField(default='No notes provided', max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Unknown Publisher', max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='tom',
            field=models.CharField(default='No data', max_length=5),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(default='No data', max_length=20),
        ),
    ]
