# Generated by Django 5.1.4 on 2024-12-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_notes_book_publisher_book_tom_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='No data', max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.CharField(default='No notes', max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='No data', max_length=64),
        ),
    ]
