# Generated by Django 5.1.4 on 2024-12-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_author_alter_book_notes_alter_book_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num',
            field=models.IntegerField(),
        ),
    ]
