# Generated by Django 5.1.5 on 2025-03-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='e_books/covers'),
        ),
    ]
