# Generated by Django 5.1.5 on 2025-03-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_books', '0002_ebook_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='cover',
        ),
    ]
