# Generated by Django 5.1.4 on 2025-01-08 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takingbook',
            name='name',
        ),
        migrations.RemoveField(
            model_name='takingbook',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='takingbook',
            name='telegram',
        ),
        migrations.AddField(
            model_name='takingbook',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='takingbook',
            name='take_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
