# Generated by Django 5.1.5 on 2025-01-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_book', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantbook',
            name='vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
