# Generated by Django 5.1.4 on 2025-01-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_book', '0002_remove_takingbook_name_remove_takingbook_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takingbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
