# Generated by Django 5.1.5 on 2025-01-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_book', '0005_wantbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wantbook',
            old_name='book_title',
            new_name='title',
        ),
    ]
