# Generated by Django 5.1.5 on 2025-01-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_book', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantbook',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('rejected', 'rejected')], default='new', max_length=10),
        ),
    ]
