# Generated by Django 5.1.5 on 2025-02-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_book', '0006_wantbook_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wantbook',
            name='votes',
        ),
    ]
