# Generated by Django 5.1.5 on 2025-01-16 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_book', '0006_rename_book_title_wantbook_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantbook',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
